global:
  resolve_timeout: 5m
  smtp_require_tls: false
  smtp_smarthost: smtp.freesmtpservers.com:25
  smtp_from: 'notifications.group@mysite.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'email@mysite.com'